Repository voxel51/api-py, pull requests merged in 2018-12, with the labels that each got.

#13 Date interface name changes
  voxel51/query.py
Labels: cleaning, documentation

#14 Adds analytic id field to job query obj
  voxel51/query.py
Labels: documentation, feature

#15 API tweaks
  docs/source/conf.py
  requirements.txt
  voxel51/api.py
Labels: enhancement

#16 Adding support for use_gpu option
  voxel51/api.py
  voxel51/query.py
Labels: feature
