Repository voxel51/api-py, pull requests merged in 2018-08, with the labels that each got.

#1 Updating documentation
  README.md
  requirements.txt
  voxel51/api.py
Labels: documentation

#2 Updating JobRequest to use analytic name, not ID
  voxel51/jobs.py
Labels: feature

#3 Updating README to use analytic name, not ID
  README.md
Labels: documentation

#4 Adding an example job for the vehicle-detector analytic
  examples.md
Labels: documentation

#5 Removing dataset stubs from API
  voxel51/api.py
Labels: cleaning

#6 Commenting out types route
  voxel51/api.py
Labels: cleaning
