Repository voxel51/api-py, pull requests merged in 2019-02, with the labels that each got.

#21 Support for analytic versions
  voxel51/jobs.py
  voxel51/query.py
Labels: feature

#20 Adding application API
  .gitignore
  README.md
  voxel51/api.py
  voxel51/apps/__init__.py
  voxel51/apps/api.py
  voxel51/apps/auth.py
  voxel51/auth.py
Labels: feature

#22 ApplicationAPI init bugfix
  voxel51/apps/api.py
Labels: bug

#23 Remove update usage limits functionality for applications
  README.md
  voxel51/apps/api.py
Labels: enhancement
