Repository voxel51/api-py, pull requests merged in 2019-04, with the labels that each got.

#34 Adds failure type as query option for jobs
  voxel51/query.py
Labels: feature

#36 Platform status route
  voxel51/api.py
  voxel51/apps/api.py
Labels: feature

#39 Fixes variable misname bug
  voxel51/api.py
  voxel51/apps/api.py
Labels: bug

#41 Adding missing slashes in route URIs
  voxel51/api.py
  voxel51/apps/api.py
Labels: bug

#43 JSON loads hotfix
  voxel51/api.py
  voxel51/apps/api.py
  voxel51/utils.py
Labels: bug

#37 Moving to compute_mode flag to control execution mode
  voxel51/api.py
  voxel51/jobs.py
  voxel51/query.py
Labels: enhancement

#44 Moving platform user functionality to a `users` subpackage
  README.md
  setup.py
  voxel51/__init__.py
  voxel51/apps/api.py
  voxel51/apps/auth.py
  voxel51/users/__init__.py
  voxel51/users/api.py
  voxel51/users/auth.py
  voxel51/users/jobs.py
  voxel51/users/query.py
  voxel51/users/utils.py
Labels: enhancement
