Repository voxel51/api-py, pull requests merged in 2019-03, with the labels that each got.

#25 Adds new job query fields
  voxel51/query.py
Labels: feature

#26 Remove statements from API
  voxel51/api.py
  voxel51/apps/api.py
Labels: cleaning

#27 Adds platform user route to delete private analytic
  voxel51/api.py
Labels: feature

#28 Adds route for applications to upload/delete custom analytics
  voxel51/api.py
  voxel51/apps/api.py
Labels: feature

#29 Adds pending analytic query field
  voxel51/query.py
Labels: enhancement

#30 Removing support_cpu/gpu flags from API methods
  voxel51/api.py
  voxel51/apps/api.py
Labels: enhancement

#31 Adds routes for job logfile stream/download url
  voxel51/api.py
Labels: feature

#32 Adding analytics routes for applications
  voxel51/apps/api.py
Labels: feature
