Repository voxel51/api-py, pull requests merged in 2020-01, with the labels that each got.

#68 Adding CLI command to get status of platform services
  voxel51/cli/cli.py
Labels: feature

#71 Adding options to print all available fields for data/jobs/analytics
  voxel51/cli/cli.py
Labels: enhancement

#72 Adding support for printing only the ID of uploaded data/jobs
  voxel51/cli/cli.py
Labels: feature

#73 Adding two useful help-related features to the CLI
  voxel51/cli/cli.py
Labels: feature

#74 Updating docs to include CLI help
  .gitignore
  APPLICATIONS.md
  CLI.md
  README.md
  docs/generate_docs.bash
  docs/source/APPLICATIONS.rst
  docs/source/CLI.rst
  docs/source/index.rst
  voxel51/cli/cli.py
Labels: documentation

#75 Clarifying that expiration date is fixed when posting data as URL
  voxel51/users/api.py
Labels: enhancement

#78 Validate search fields client-side
  voxel51/users/query.py
Labels: bug

#76 Adding CLI support for posting data as URL, and clarifying analytic image upload
  CLI.md
  pylintrc
  voxel51/apps/api.py
  voxel51/cli/cli.py
  voxel51/users/api.py
  voxel51/users/query.py
Labels: feature

#79 CLI tab completion
  CLI.md
  requirements.txt
  voxel51/cli/cli.py
Labels: feature

#77 Rely on backend for batch error formatting
  voxel51/users/api.py
Labels: enhancement

#70 Updating parsing of batch action failures
  voxel51/cli/cli.py
Labels: enhancement, future release

#81 Adding support for setting token private key via environment variable
  APPLICATIONS.md
  CLI.md
  README.md
  pylintrc
  voxel51/apps/api.py
  voxel51/apps/auth.py
  voxel51/cli/cli.py
  voxel51/users/api.py
  voxel51/users/auth.py
Labels: feature

#82 Use platform status message format from API
  voxel51/cli/cli.py
  voxel51/users/query.py
Labels: enhancement, future release

#84 Specify dependencies in setup.py
  MANIFEST.in
  README.md
  install.bash
  requirements.txt
  setup.py
  voxel51/constants.py
  voxel51/version.json
Labels: feature

#85 Walkthrough
  .gitignore
  CLI.md
  README.md
  WALKTHROUGH.md
  docs/source/WALKTHROUGH.rst
  docs/source/conf.py
  docs/source/index.rst
  setup.py
  voxel51/cli/cli.py
Labels: documentation

#87 Adding support for loading Tokens from dict/str
  voxel51/users/auth.py
Labels: enhancement

#89 Adding method to get analytic ID by name + version
  voxel51/users/api.py
  voxel51/users/query.py
Labels: feature
